### The conventional way to import the package is as follows:

In [31]:
import numpy as np

### Let’s create our first NumPy array. It can be done simply by passing in a Python list!

In [32]:
lst = [2, 4, 6, 8, 13, 2020]
numpy_arr = np.array(lst)
numpy_arr

array([   2,    4,    6,    8,   13, 2020])

### A 2 dimensional array (also can be called a matrix) is simply a list of lists, so we can just pass that in:

In [33]:
lst_2d = [[3, 5, 7, -4, 1], [0, 5, 33, -750, 2]]
numpy_arr_2d = np.array(lst_2d)
numpy_arr_2d

array([[   3,    5,    7,   -4,    1],
       [   0,    5,   33, -750,    2]])

### Shape
We can verify how many dimensions our array is and how big each one is. This is very important, especially when dealing with mathematical functions.

In [34]:
numpy_arr.shape

(6,)

In [35]:
numpy_arr_2d.shape

(2, 5)

 You can reshape dimensions with NumPy arrays as long as the elements required for reshaping are equal in both shapes.

In [36]:
numpy_arr.reshape((3,2))

array([[   2,    4],
       [   6,    8],
       [  13, 2020]])

In [38]:
numpy_arr_2d.reshape((3,5))

ValueError: cannot reshape array of size 10 into shape (3,5)

Specifying one of the shapes to be -1 tells NumPy to figure out the size of that dimension,
as long as you specify the other dimension sizes. In this case, numpy_arr_2d, originally a 2x5 matrix, figures out that if you want 2 columns, automatically the other dimension size is 5

In [39]:
numpy_arr_2d.reshape((-1, 2))

array([[   3,    5],
       [   7,   -4],
       [   1,    0],
       [   5,   33],
       [-750,    2]])

### Indexing:
Indexing and slicing is done the exact same way as you would for a regular old Python list.

In [40]:
numpy_arr[1]

4

In [42]:
numpy_arr[-2:]

array([  13, 2020])

Say that we want to get only the second column from numpy_arr_2d. Each dimension is delimited by a comma.the colon says that we want all the elements of that dimension.

In [44]:
numpy_arr_2d[1,:]

array([   0,    5,   33, -750,    2])

### Mathematical Functions:
Some basic functions include finding the min/max value, the mean and the median.
For many functions you can specify which axis (dimension) you want the calculation.

In [45]:
np.mean(numpy_arr)

342.1666666666667

In [46]:
np.median(numpy_arr)

7.0

In [47]:
numpy_arr.min()

2

In [48]:
numpy_arr.max()

2020

Here we specify we want to find the mean of the 2nd dimension (ie each of the columns)

In [53]:
np.mean(numpy_arr_2d, 1)

array([   2.4, -142. ])

### Mathematical Operations:
What if I want to add 5 to each element? Or raise each element to the power of 3?

In [54]:
print(numpy_arr)
print(numpy_arr + 5)
print(numpy_arr ** 3)

[   2    4    6    8   13 2020]
[   7    9   11   13   18 2025]
[         8         64        216        512       2197 -347526592]


In [ ]:
You can perform operations on one array to another.
#arange is NumPy's version of the Python's range function
#the dot product of 2 matrices

In [55]:
a = np.arange(9).reshape((3,3))
print(a)
print("\n")
b = np.arange(20, 11, -1).reshape((3,3))
print(b)
print("\n")
print(a + b)
print("\n")
print(a * b)
print("\n")
print(np.dot(a, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[20 19 18]
 [17 16 15]
 [14 13 12]]


[[20 20 20]
 [20 20 20]
 [20 20 20]]


[[ 0 19 36]
 [51 64 75]
 [84 91 96]]


[[ 45  42  39]
 [198 186 174]
 [351 330 309]]


### Nan
nan is basically a numerical datatype that represents an undefined value. 
For example if you try to divide a NumPy array by 0, you will get an array full of nan‘s. 
Most real life data has undefined or unknown values and we will see this and deal with it a lot

In [56]:
np.nan

nan

In [57]:
numpy_arr/0

<ipython-input-57-0fc8f679bef7>:1: RuntimeWarning: divide by zero encountered in true_divide
  numpy_arr/0


array([inf, inf, inf, inf, inf, inf])

## Exercise

In [30]:
def np_calc(arr):
    return arr.min(),np.std(arr),np.prod(arr),np.dot(arr,arr),arr-4

arr_min,arr_std,arr_prod,arr_dot,arr_minus_four=np_calc(numpy_arr)
print(arr_min)
print("\n")
print(arr_std)
print("\n")
print(arr_prod)
print("\n")
print(arr_dot)
print("\n")
print(arr_minus_four)

2


750.3577850302851


10083840


4080689


[  -2    0    2    4    9 2016]


In [1]:
pip install pandas

     |████████████████████████████████| 10.3 MB 2.6 MB/s            
     |████████████████████████████████| 503 kB 7.9 MB/s            
Note: you may need to restart the kernel to use updated packages.
